apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    name: hasura
    app: hasura
  name: hasura
spec:
  source:
    type: Git
    git:
      uri: https://github.com/viaacode/hasura-openshift-jenkins.git

  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
