apiVersion: v1
kind: Template
metadata:
  annotations:
  creationTimestamp: null
  name: postgresql
objects:

  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: postgres-${ENV}
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: postgres-${ENV}
        spec:

          containers:
            - name: postgres
              image: docker.io/postgres@sha256:97fcdcff5106e995661864bebf1fd6881553471b88e2afd6f98fbcb775bf66b7
              imagePullPolicy: "IfNotPresent"
              ports:
                - containerPort: 5432
              envFrom:
                - configMapRef:
                    name: postgres-${ENV}cnf
              volumeMounts:
                - mountPath: /var/lib/postgresql/data
                  name: postgresdb-${ENV}
              resources:
                    limits:
                      cpu: 900m
                      memory: ${MEMORY_LIMIT}
                    requests:
                      cpu: 100m
                      memory: 512Mi
          volumes:
            - name: postgresdb-${ENV}
              persistentVolumeClaim:
                claimName: postgres-${ENV}-pv-claim
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: postgres-${ENV}cnf
      labels:
        app: postgres-${ENV}
    data:
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations:
        volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/vsphere-volume
      creationTimestamp: null

      labels:
        ENV: ${ENV}
        app: hasura-${ENV}
      name: postgres-${ENV}-pv-claim
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: ${VOLUME_CAPACITY}
      storageClassName: vsphere-standard
    status: {}

  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: postgres-${ENV}
      name: ${DATABASE_SERVICE_NAME}
    spec:
      ports:
      - protocol: TCP
        port: 5432
        targetPort: 5432

      selector:
        app: postgres-${ENV}
      type: LoadBalancer



parameters:
- description: Maximum amount of memory the container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 512Mi

- description: The name of the OpenShift Service exposed for the database.
  displayName: Database Service Name
  name: DATABASE_SERVICE_NAME
  required: true
  value: postgresql-tst
- description: Username for PostgreSQL user that will be used for accessing the
    database.
  displayName: PostgreSQL Connection Username
  from: user[A-Z0-9]{3}
  generate: expression
  name: POSTGRESQL_USER
  required: true
- description: Password for the PostgreSQL connection user.
  displayName: PostgreSQL Connection Password
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  name: POSTGRESQL_PASSWORD
  required: true
- description: Name of the PostgreSQL database accessed.
  displayName: PostgreSQL Database Name
  name: POSTGRESQL_DATABASE
  required: true
  value: sampledb
- description: Volume space available for data, e.g. 512Mi, 2Gi.
  displayName: Volume Capacity
  name: VOLUME_CAPACITY
  required: true
  value: 1Gi

- name: ENV
  value: tst
